default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PLANET_NINE_DATABASE_HOST'] %>
  username: <%= ENV['PLANET_NINE_DATABASE_USERNAME'] %>
  password: <%= ENV['PLANET_NINE_DATABASE_PASSWORD'] %>
  database: <%= ENV['PLANET_NINE_DATABASE_NAME'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default

test:
  <<: *default
  database: planet_nine_test

production:
  <<: *default
